menu:
  - {name: 'projects', url: '/projects'}
  - {name: 'resume', url: '/resume'}
  - {name: 'contact', url: '/contact'}

projects:
# - {name: 'Project Template', type: 'Personal Project', year: '2026', info: 'Brief technical summary of your project scope, hardware/software stack, and performance metrics.', image: 'assets/img/placeholder.jpg', url: 'project-two', show_more_info: false}

awards: []
# - {name: 'Award Name', type: 'Organization / Competition', year: '2026', info: 'Award details', image: 'assets/img/award.jpg'}

courses: []
# - {name: 'Course Name', url: 'course-slug'}

social:
  - {icon: 'linkedin', link: 'https://www.linkedin.com/in/christianduggan'}

links: []
# - {title: 'GitHub', url: 'https://github.com/C-Duggan', description: 'Source code & repositories'}

contacts:
  - {name: 'Christian Duggan', department: 'Mechanical Engineering', institution: 'University of Florida', location: 'Gainesville, Florida', phone: '+1 727 401 6418', email: 'c.duggan@ufl.edu', personal_email: 'cduggan600@gmail.com', image: 'assets/img/christian.jpg'}
